### ISSUE TITLE
Error in 10.8.1 

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/Extract-CLU-Tool#7]
Ok, I was able to successfully extract two HUC12 CLU's using the tool, and then it just started failing.  I removed, deleted, etc... and it is still failing.  

![error_3_16_21](https://user-images.githubusercontent.com/63659670/111383962-ef100700-8676-11eb-98c8-8b2ce1f405bb.JPG)

**Comment by misti-wudtke-nrcs** [comment]
This entire tool is unnecessary at this point because you can use the built-in "Feature Class to Feature Class" geoprocessing tool in ArcGIS Pro to extract features from the CLU service to a local file geodatabase.

**Comment by CEM-NRCS** [comment]
Misti, what is the URL of the CLU Feature Service you are using as input to the Feature Class to Feature Class tool?

**Comment by japitts8816** [comment]
I got it working.  IDK if it was because I was using a FGDB to put the extracts that was in the same location as another FGDB I was using or, if I wasn't saving it, or IDK.  I created a new FGDB in a different folder location to drop the extracts and it seemed to work fine after that.

**Comment by japitts8816** [comment]
Misti, I started a State FC2FC extract from the services on GP and already it's been about 20 minutes and it's only 6% complete.  I'm on a great internet service.  Did it take awhile to get your State extracted?  I'm finding that I still have to put the CLU data on the servers in the counties.  That's why I like this tool so much.  And to extract CLU data for specific MRBI HUC12s - it's a dream.  Maybe I'll try a smaller FC2FC extract vs the entire state.  Apprec Everyone!

**Comment by CEM-NRCS** [comment]
I'm getting variable results with Feature Class to Feature Class using the rest Feature Service on GeoPortal (not the one in App Server, which I can't seem to load in an ESRI product and may just be missing a step).

Some tracts it finds. Others it doesn't. When it doesn't, it seems to lock up at 6% progress while it tries to query all tracts to find the record(s) in question (from a given query in the tool). If the query doesn't hit a particular tract number if the first few hundred thousand returns, it just runs and runs (possibly bogging down GeoPortal in the process). Eventually, FC2FC did seem to find the tract I was looking for in this case, but it took 3 minutes to come up for one small tract with just 3 fields. And Indiana has I think, less than 2 million fields. A smaller state might go faster, but a larger state probably takes longer to filter. Another attempt with FC2FC on the same tract "timed out" and returned empty geometry. This could be happening at a larger scale too, like Julie's case, where even if a county comes up in the filters, the FC2FC tool needs to fetch all fields that are in that county, which could take it a while to get through the host table and find them.

In other cases, when the tract I want happens to come up in the initial query builder dropdowns and I can pick it instead of typing it in, FC2FC runs extremely fast. A matter of seconds.

On balance, however, I would have GeoPortal performance concerns if we started making FC2FC the standard procedure in local tools and users started doing individual tract queries that would run for many minutes while using it. Multiply the users and the multi-minute queries, and things could start to bog down. Travis Rome talked about querying large datasets (NPAD in his example) as being one of their performance concerns with with the various hosted products.

I've also put in a question to the GeoPortal team about the timing of the Feature Service updates for the GeoPortal copy, rather than the Appserver based one that the Extract tool is using. We already know the AppServer copy updates near real time, because it has to in order to support CD. The other copy on GeoPortal from NRCS Curated, is where I have the question. It may be as fast as near real time as well, but I want to be sure. Hopefully the Service Now crew can clarify exactly what the syncing/updating schedule is for that service.

**Comment by misti-wudtke-nrcs** [comment]
Hi Chris! I've used this service:

https://gis.sc.egov.usda.gov/appserver/rest/services/common_land_units/common_land_units/FeatureServer/0


Misti Wudtke

State GIS Specialist

USDA NRCS Vermont

356 Mountain View Dr, Suite 105

Colchester, VT 05446

o: (802) 951-6796 x249

m: (608) 630-0390

***@***.******@***.***>

________________________________

**Comment by misti-wudtke-nrcs** [comment]
It absolutely does take a while! It takes about 20 minutes to complete just for Vermont--and it says it's stuck at 6% right up until its finished.
________________________________

**Comment by CEM-NRCS** [comment]
OK. Yeah. That's the one I've been trying to. The URL is as you say:
https://gis.sc.egov.usda.gov/appserver/rest/services/common_land_units/common_land_units/FeatureServer/0

That is the same one the extract tool is using. I'll cancel my ServiceNow ticket.

So the only concern still remains the filtering issue called by ESRI's built-in query tools/functions.

**Comment by misti-wudtke-nrcs** [comment]
It definitely takes a while to execute--about 20 minutes or so just for Vermont, and it always sits there at 6%--but then suddenly it's finished.

I haven't tried it on a bigger subset of data than VT; possibly if I ran into issues I may download in a couple of smaller queries? Or maybe for bigger states it does just get bogged down and may not work. I only know that I couldn't get the Extract CLU tool to work in Pro 2.6, whereas FC2FC did work; that's why I was using FC2FC.

I also haven't used FC2FC for querying individual tracts. In fact, the reason I needed to download CLU data in the first place is because we here in VT couldn't get simple Select by Attributes to work on the service layer (we submitted a ticket as to why and never heard back--but maybe the reply below answered this question?). I just needed a means to download VT and re-publish as our own hosted feature layer for VT, on which people could run Select by Attributes for the mobile maps we're building. Hopefully this workflow--although it involves duplicated data--won't impinge on the original service the way you've described.

________________________________
